### PR TITLE
flex-initramfs: fix IMAGE_FSTYPES

### PR DESCRIPTION
**Pull request by aarslan7**
IMAGE_FSTYPES override was recently updated which causes flex-initramfs-image to generate a wic.gz image instead of cpio which is the required type. Use a higher precedence override in the recipe to fix this behaviour.

JIRA: SB-21747

### CODE REVIEW

**Comment by aarslan7** [comment]
@Noor-Ahsan these need to be reverted as they will not be needed:
https://github.com/MentorEmbedded/meta-flex-ref-bsps/pull/100
https://github.com/MentorEmbedded/meta-flex-ref-bsps/pull/99

**Comment by aarslan7** [comment]
testing a build. will inform when done

**Comment by aarslan7** [comment]
build passed

**Comment by Noor-Ahsan** [comment]
> @Noor-Ahsan these need to be reverted as they will not be needed: [MentorEmbedded/meta-flex-ref-bsps#100](https://github.com/MentorEmbedded/meta-flex-ref-bsps/pull/100) [MentorEmbedded/meta-flex-ref-bsps#99](https://github.com/MentorEmbedded/meta-flex-ref-bsps/pull/99)

where we will be moving these?

**Comment by aarslan7** [comment]
> > @Noor-Ahsan these need to be reverted as they will not be needed: [MentorEmbedded/meta-flex-ref-bsps#100](https://github.com/MentorEmbedded/meta-flex-ref-bsps/pull/100) [MentorEmbedded/meta-flex-ref-bsps#99](https://github.com/MentorEmbedded/meta-flex-ref-bsps/pull/99)
> 
> where we will be moving these?

I had a discussion with @abelal . the IMAGE_FSTYPES needs to be wic.gz for most recipes e.g. archive-release, service-installer, etc. initramfs is a special case, so we need to override that only

**Comment by Noor-Ahsan** [comment]
> > > @Noor-Ahsan these need to be reverted as they will not be needed: [MentorEmbedded/meta-flex-ref-bsps#100](https://github.com/MentorEmbedded/meta-flex-ref-bsps/pull/100) [MentorEmbedded/meta-flex-ref-bsps#99](https://github.com/MentorEmbedded/meta-flex-ref-bsps/pull/99)
> > 
> > 
> > where we will be moving these?
> 
> I had a discussion with @abelal . the IMAGE_FSTYPES needs to be wic.gz for most recipes e.g. archive-release, service-installer, etc. initramfs is a special case, so we need to override that only

will you send another PR?

**Comment by aarslan7** [comment]
> > > > @Noor-Ahsan these need to be reverted as they will not be needed: [MentorEmbedded/meta-flex-ref-bsps#100](https://github.com/MentorEmbedded/meta-flex-ref-bsps/pull/100) [MentorEmbedded/meta-flex-ref-bsps#99](https://github.com/MentorEmbedded/meta-flex-ref-bsps/pull/99)
> > > 
> > > 
> > > where we will be moving these?
> > 
> > 
> > I had a discussion with @abelal . the IMAGE_FSTYPES needs to be wic.gz for most recipes e.g. archive-release, service-installer, etc. initramfs is a special case, so we need to override that only
> 
> will you send another PR?

no. there is no change required in meta-flex-ref-bsps for this

**Review by abelal — APPROVED** [review]

**Pull request merged**
