### PR TITLE
Remove meta-gplv2 content

### PR DESCRIPTION
**Pull request by kergoth**
This layer is unsupported upstream.

### CODE REVIEW

**Comment by Noor-Ahsan** [comment]
@kergoth @abelal yes we will not provide/test gplv2 but the option should remain there for services/customers

**Comment by kergoth** [comment]
[**@Noor-Ahsan**](https://github.com/Noor-Ahsan) commented on [Jul 27, 2022, 10:13 AM MST](https://github.com/MentorEmbedded/meta-sokol-flex/pull/9#issuecomment-1197062924 "2022-07-27T17:13:56Z - Replied by Github Reply Comments"):
> @kergoth @abelal yes we will not provide/test gplv2 but the option should remain there for services/customers

meta-gplv2 doesn't even have a functioning master branch. The yocto project officially no longer supports the layer, due to constant problems with trying to maintain ancient versions of projects. There are better ways to support non-gplv3 builds going forward, such as using BSD/MIT components.

**Comment by Noor-Ahsan** [comment]
on master they have removed the layer.conf https://git.yoctoproject.org/meta-gplv2/commit/ but they still have kirkstone layer https://git.yoctoproject.org/meta-gplv2/tree/?h=kirkstone

**Comment by kergoth** [comment]
[**@Noor-Ahsan**](https://github.com/Noor-Ahsan) commented on [Jul 29, 2022, 8:31 AM MST](https://github.com/MentorEmbedded/meta-sokol-flex/pull/9#issuecomment-1199544401 "2022-07-29T15:31:38Z - Replied by Github Reply Comments"):
> on master they have removed the layer.conf https://git.yoctoproject.org/meta-gplv2/commit/ but they still have kirkstone layer https://git.yoctoproject.org/meta-gplv2/tree/?h=kirkstone

Well spotted, I'll rebase this on main rather than kirkstone, we can merge it there and postpone it on kirkstone for now.

**Comment by kergoth** [comment]
@abelal @Noor-Ahsan Rebased on main after merging kirkstone to main.

**Review by abelal — APPROVED** [review]

**Comment by kergoth** [comment]
As this is main, not kirkstone, went ahead and merged it.

**Pull request merged**
