### PR TITLE
sokol-flex.conf: replace connman with systemd-networkd

### PR DESCRIPTION
**Pull request by ahsanhussain**
Change our default network manager as Systemd works well enough for our
advertised use-cases and it is well-documented by the community.
Similarly for DNS resolution we can use systemd-resolved instead of
Avahi.

Jira-ID: SB-22665

### CODE REVIEW

**Comment by ahsanhussain** [comment]
Tested on Qemu aarch64. Works well and also saves a couple of seconds of boot time on Qemu.

```bash
# ping -c1 www.google.com
PING www.google.com (142.250.181.164): 56 data bytes
64 bytes from 142.250.181.164: seq=0 ttl=112 time=32.199 ms

--- www.google.com ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 32.199/32.199/32.199 ms
```

**Comment by abelal** [comment]
I believe @Noor-Ahsan asked someone to create a ticket for this. Can we get that here for tracking purposes?

**Comment by abelal** [comment]
There's some connman related stuff under the staging layer as well. Maybe we should take care of that here as well?

**Comment by ahsanhussain** [comment]
> There's some connman related stuff under the staging layer as well. Maybe we should take care of that here as well?

Done

**Comment by ahsanhussain** [comment]
> I believe @Noor-Ahsan asked someone to create a ticket for this. Can we get that here for tracking purposes?

Done

**Review by abelal — APPROVED** [review]

**Pull request merged**
