### PR TITLE
Implement jobs/threads scaling support

### PR DESCRIPTION
**Pull request by kergoth**
A new class is added warns if memory-per-cpu-core is low, and set
BB_NUMBER_THREADS_SCALED and PARALLEL_MAKE_SCALED with scaled down
values.

Class behavior is configured using the MEM_PER_CPU_SCALING_THRESHOLDS
variable. By default, if we have less than 4gb per CPU core, we warn and
reduce the make jobs to cpus/2. If we have less than 2gb per CPU core,
we warn and reduce both bitbake threads and make jobs to cpus/2.

An example of how to set the variables to the scaled values is provided in
local.conf.sample.

JIRA: SB-20030

### CODE REVIEW

**Comment by kergoth** [comment]
@abelal When migrating this, I realigned the config based on your request, which is less aggressive, and corrected the typo you noticed.

**Comment by kergoth** [comment]
Updated to add example output messages to the commit message.

**Comment by kergoth** [comment]
Updated the commit message further to include a mention of the variable that controls the behavior, as well as the default configuration used.

**Comment by ahsanhussain** [comment]
LGTM

**Comment by kergoth** [comment]
[**@ahsanhussain**](https://github.com/ahsanhussain) commented on [Aug 3, 2022, 4:24 AM MST](https://github.com/MentorEmbedded/meta-sokol-flex/pull/13#issuecomment-1203819251 "2022-08-03T11:24:26Z - Replied by Github Reply Comments"):
> LGTM

Hmm, I was looking at this and realizing that it also sets the jobs/threads default value, not only in the case where we need to scale down. I'm wondering if I should change this to only alter the already set values. That is, the user can currently override the jobs and threads vars in local.conf, but their default values aren't currently coming from oe-core, they're also set by the variable that controls this.

Thoughts? Should it only change jobs/threads when we're scaling down, or also set the default value?

**Comment by abelal** [comment]
> [**@ahsanhussain**](https://github.com/ahsanhussain) commented on [Aug 3, 2022, 4:24 AM MST](https://github.com/MentorEmbedded/meta-sokol-flex/pull/13#issuecomment-1203819251):
> 
> > LGTM
> 
> Hmm, I was looking at this and realizing that it also sets the jobs/threads default value, not only in the case where we need to scale down. I'm wondering if I should change this to only alter the already set values. That is, the user can currently override the jobs and threads vars in local.conf, but their default values aren't currently coming from oe-core, they're also set by the variable that controls this.
> 
> Thoughts? Should it only change jobs/threads when we're scaling down, or also set the default value?

@kergoth I think we should pick the defaults from oe-core and only scale down when there's a need.

**Comment by kergoth** [comment]
[**@abelal**](https://github.com/abelal) commented on [Aug 3, 2022, 8:48 AM MST](https://github.com/MentorEmbedded/meta-sokol-flex/pull/13#issuecomment-1204136014 "2022-08-03T15:48:58Z - Replied by Github Reply Comments"):
> > [**@ahsanhussain**](https://github.com/ahsanhussain) commented on [Aug 3, 2022, 4:24 AM MST](https://github.com/MentorEmbedded/meta-sokol-flex/pull/13#issuecomment-1203819251):
> > 
> > > LGTM
> > 
> > Hmm, I was looking at this and realizing that it also sets the jobs/threads default value, not only in the case where we need to scale down. I'm wondering if I should change this to only alter the already set values. That is, the user can currently override the jobs and threads vars in local.conf, but their default values aren't currently coming from oe-core, they're also set by the variable that controls this.
> > 
> > Thoughts? Should it only change jobs/threads when we're scaling down, or also set the default value?
> 
> @kergoth I think we should pick the defaults from oe-core and only scale down when there's a need.

That was my thought as well, I'll test that out. Thanks

**Comment by kergoth** [comment]
@abelal Please re-review.

**Review by abelal — APPROVED** [review]

**Comment by Noor-Ahsan** [comment]
Missing license header from bbclass. See example at https://github.com/MentorEmbedded/meta-mentor/blob/dunfell/meta-mel-support/classes/image-sanity-incompatible.bbclass#L1

**Comment by kergoth** [comment]
[**@kergoth**](https://github.com/kergoth) commented on [Aug 4, 2022, 7:56 AM MST](https://github.com/MentorEmbedded/meta-sokol-flex/pull/13#issuecomment-1205371839 "2022-08-04T14:56:10Z - Replied by Github Reply Comments"):
> > Missing license header from bbclass. See example at [https://github.com/MentorEmbedded/meta-mentor/blob/dunfell/meta-mel-support/classes/image-sanity-incompatible.bbclass#L1](https://github.com/MentorEmbedded/meta-mentor/blob/dunfell/meta-mel-support/classes/image-sanity-incompatible.bbclass?rgh-link-date=2022-08-04T12%3A24%3A53Z#L1)
> 
> Good eye, thanks!

Added license header. Thanks.

**Comment by Noor-Ahsan** [comment]
@kergoth Just for my understanding this will update the values that we have set in local.conf? for example if we have folowing in local.conf the implementation above will overwrite it?

BB_NUMBER_THREADS ?= "${@int(oe.utils.cpu_count() * 1.5)}"
PARALLEL_MAKE ?= "-j ${@oe.utils.cpu_count() * 2}"

**Comment by kergoth** [comment]
[**@Noor-Ahsan**](https://github.com/Noor-Ahsan) commented on [Aug 12, 2022, 12:01 AM MST](https://github.com/MentorEmbedded/meta-sokol-flex/pull/13#issuecomment-1212793145 "2022-08-12T07:01:39Z - Replied by Github Reply Comments"):
> [@kergoth](https://github.com/kergoth) Just for my understanding this will update the values that we have set in local.conf? for example if we have folowing in local.conf the implementation above will overwrite it?
> 
> BB\_NUMBER\_THREADS ?= "${[@int](https://github.com/int)(oe.utils.cpu\_count() \* 1.5)}"  
> PARALLEL\_MAKE ?= "-j ${@oe.utils.cpu\_count() \* 2}"

The original implementation would not, the new one will, but only in the case where resources are limited. Maybe we should think about the semantics again. The intention of having it not define it for the default case was to allow the oe-core default to take effect when we aren't scaling down, but as a consequence of the implementation change, now it overrides user configuration when scaling.

**Comment by abelal** [comment]
> [**@Noor-Ahsan**](https://github.com/Noor-Ahsan) commented on [Aug 12, 2022, 12:01 AM MST](https://github.com/MentorEmbedded/meta-sokol-flex/pull/13#issuecomment-1212793145):
> 
> > [@kergoth](https://github.com/kergoth) Just for my understanding this will update the values that we have set in local.conf? for example if we have folowing in local.conf the implementation above will overwrite it?
> > BB_NUMBER_THREADS ?= "${[@int](https://github.com/int)(oe.utils.cpu_count() * 1.5)}"
> > PARALLEL_MAKE ?= "-j ${@oe.utils.cpu_count() * 2}"
> 
> The original implementation would not, the new one will, but only in the case where resources are limited. Maybe we should think about the semantics again. The intention of having it not define it for the default case was to allow the oe-core default to take effect when we aren't scaling down, but as a consequence of the implementation change, now it overrides user configuration when scaling.

Hmmm. The MR says "help the customer", maybe we could just warn in case of resource limitations and provide an appropriate suggestion rather than overriding? We could also provide a variable through local.conf which could manipulate this behavior, sounds like an overkill / over-worked feature?

**Comment by kergoth** [comment]
@abelal @Noor-Ahsan Reworked to simplify and set optionally used variables. I also changed the default scaling values, as expecting 8gb per core seems unrealistic.

**Comment by abelal** [comment]
If the build is using scaled values we shouldn't generate the warning.

**Comment by kergoth** [comment]
[**@abelal**](https://github.com/abelal) commented on [Sep 6, 2022, 8:40 AM MST](https://github.com/MentorEmbedded/meta-sokol-flex/pull/13#issuecomment-1238323816 "2022-09-06T15:40:10Z - Replied by Github Reply Comments"):
> If the build is using scaled values we shouldn't generate the warning.

Updated. Now we only show messages if we would be changing the values, and we never show anything if the user has already switched to use the scaled values, or if they've manually corrected them. It also shows a more detailed message with the suggested change:
```
WARNING: Low memory per CPU core (~3 Gb) in this system. You may wish to reduce PARALLEL_MAKE to 16 or less in local.conf.
```

**Review by abelal — APPROVED** [review]

**Pull request merged**
