### PR TITLE
sokol-flex: add libxcrypt to the multilib runtime packages

### PR DESCRIPTION
**Pull request by kergoth**
This is expected to already be installed by Sourcery Analyzer.

JIRA: SB-22571

### CODE REVIEW

**Comment by tsiddiq** [comment]
https://jira.alm.mentorg.com/browse/SB-22571?focusedCommentId=920668&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-920668

**Comment by kergoth** [comment]
@Noor-Ahsan  This was tested and should be ready for merge.

**Review by tsiddiq — APPROVED** [review]

**Comment by tsiddiq** [comment]
Yes I had tested it up. It is perfectly working fine https://jira.alm.mentorg.com/browse/SB-22571?focusedCommentId=921005&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-921005

Note: there was another issue. May be out of scope of this issue https://jira.alm.mentorg.com/browse/SB-22565?focusedCommentId=921006&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-921006

**Comment by Noor-Ahsan** [comment]
> Note: there was another issue. May be out of scope of this issue https://jira.alm.mentorg.com/browse/SB-22565?focusedCommentId=921006&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-921006

This is already fixed and merged

**Pull request merged**
