### PR TITLE
mem-per-cpu-scaling.bbclass: allow opt-out of the message

### PR DESCRIPTION
**Pull request by kergoth**
MEM_PER_CPU_MESSAGE may be set to 0 to disable the warning/error
message.

### CODE REVIEW

**Comment by kergoth** [comment]
This also updates the displayed message to show the user how to opt-out:
```
WARNING: Low memory per CPU core (~3 Gb) in this system. You may wish to reduce PARALLEL_MAKE to 16 or less in local.conf, or set MEM_PER_CPU_MESSAGE="0" to disable this messa
ge.
```

**Comment by kergoth** [comment]
This also updates the displayed message to show the user how to opt-out:
```
WARNING: Low memory per CPU core (~3 Gb) in this system. You may wish to reduce PARALLEL_MAKE to 16 or less in local.conf, or set MEM_PER_CPU_MESSAGE="0" to disable this messa
ge.
```

**Comment by abelal** [comment]
Hmmmmmm. I am getting a little confused here sorry. The idea that I tried to convey was to have a local.conf switch e.g. AUTOSCALE_MEM_PER_CPU. If not set we print out warnings/errors as in the usual way. If set, we auto-scale and say nothing. Would that be more user friendly?

**Comment by kergoth** [comment]
[**@abelal**](https://github.com/abelal) commented on [Sep 8, 2022, 5:20 AM MST](https://github.com/MentorEmbedded/meta-sokol-flex/pull/47#issuecomment-1240642718 "2022-09-08T12:20:54Z - Replied by Github Reply Comments"):
> Hmmmmmm. I am getting a little confused here sorry. The idea that I tried to convey was to have a local.conf switch e.g. AUTOSCALE_MEM_PER_CPU. If not set we print out warnings/errors as in the usual way. If set, we auto-scale and say nothing. Would that be more user friendly?

That's what it already does. This lets you disable the message *without* using that local.conf switch. If I know my builds will succeed with the current configuration and I don't *want* to used scaled down values, but my current ones, this lets me disable the resource check entirely.

**Comment by abelal** [comment]
@kergoth thanks for the clarification.

**Review by abelal — APPROVED** [review]

**Pull request merged**
